version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - booknetwork
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: books_api
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: book_user
      MYSQL_PASSWORD: book_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - booknetwork

  nginx:
    image: nginx:latest
    container_name: books_api_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - booknetwork

networks:
  booknetwork:

volumes:
  db_data:
